Merge: this changes will solve Security Issues
liz-segura98/mattermost-app-pagerduty pull request #1
Opened 2023-01-18 18:25 UTC by liz-segura98

This PR will solve all the security issues reported on current open PR and Mattermost Channel:

- Link to PR [(mattermost-app-pagerduty)](https://github.com/mattermost/mattermost-app-pagerduty/pull/2)
- Link to Security Issues comment [(security-issues-report)](https://community.mattermost.com/core/pl/sojqu6kie3yexyhimi36ib3pnh)

2023-01-24 18:31 UTC, mickmister requested changes

2023-01-24 18:31 UTC, mickmister commented on src/api/index.ts
> +router.post(`${Routes.App.CallPathDisconnectSubmit}`, requireUserOAuthConnected, cConfigure.fOauth2Disconnect);
We should `requireUserOAuthDisconnected` for the `/connect` call

2023-01-24 18:31 UTC, mickmister commented on src/utils/exception.ts
> +        logger.error({ message, siteUrl, requestPath });
Is it appropriate to log the error during this object's construction? Do we log elsewhere as well?

2023-01-24 18:31 UTC, mickmister commented on src/restapi/middleware.ts
> +    const oauth2: Oauth2App = call.context.oauth2 as Oauth2App;
Let's avoid the `as ...` in these middleware functions for the individual fields in the HTTP body. We should assume this could be undefined, and we should let the typescript compiler take care of ensuring we check that it's defined.

```suggestion
    const oauth2: Oauth2App | undefined = call.context.oauth2;
```

2023-01-26 16:26 UTC, liz-segura98 commented on src/utils/exception.ts
> +        logger.error({ message, siteUrl, requestPath });
It was designed like that to be used in case the Exception is shown when an HTTP petition is done, so we can catch the real error, but still display an user friendly error to the user

2023-01-27 20:45 UTC, liz-segura98 commented on src/restapi/middleware.ts
> +    const oauth2: Oauth2App = call.context.oauth2 as Oauth2App;
This was fixed in commit [77c8af7](https://github.com/liz-segura98/mattermost-app-pagerduty/pull/1/commits/77c8af7e187a49c7fd4f2ce3f808a9181071ba55)

2023-01-27 20:46 UTC, liz-segura98 commented on src/api/index.ts
> +router.post(`${Routes.App.CallPathDisconnectSubmit}`, requireUserOAuthConnected, cConfigure.fOauth2Disconnect);
This was solved in commit [6411847](https://github.com/liz-segura98/mattermost-app-pagerduty/pull/1/commits/64118477e81e94aade17486209632308361e690d)

2023-01-30 09:43 UTC, srkgupta commented on src/forms/add-note-incident.ts
> +    const pdToken: PagerDutyOpts = returnPagerdutyToken(call);
Shouldnt we add a step here to check if the pdToken is null or empty, then return. Does the `throw new Exception(` in `returnPagerdutyToken` function will automatically handle and return from the `addNoteOpenModal` function?

2023-01-30 16:04 UTC, liz-segura98 commented on src/forms/add-note-incident.ts
> +    const pdToken: PagerDutyOpts = returnPagerdutyToken(call);
On the function, we already handle if the oauth or the token are missing. So we know, whenever the value is returned is because a token was found. If there was the case, the flow will be interrupted from there

```

export function returnPagerdutyToken(call: AppCallRequest): PagerDutyOpts {
    const i18nObj = configureI18n(call.context);
    const oauth2: Oauth2App | undefined = call.context.oauth2;
    if (!oauth2) {
        throw new Exception(ExceptionType.TEXT_ERROR, i18nObj.__('general.validation-user.oauth2-not-found'), i18nObj.__('general.validation-user.oauth2-not-found'), call);
    }

    const userToken = oauth2.user?.token;
    if (!userToken) {
        throw new Exception(ExceptionType.TEXT_ERROR, i18nObj.__('general.validation-user.oauth2-not-found'), i18nObj.__('general.validation-user.oauth2-not-found'), call);
    }

    return { token: userToken, tokenType: 'bearer' };
}
```

2023-02-01 06:37 UTC, srkgupta approved these changes
Thanks @liz-segura98. The changes LGTM from security perspective. Great work.

2023-02-01 17:19 UTC, merged